### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by zoomlogo** [PyGamer0/51AC8#3]
This issue will a todo list.

- [ ] Add:
    - [x] `1/2 (symbol)` to split strings / arrays into half.
    - [x] `String` (chars) equality.
    - [x] More numpy array things.
    - [x] Sorting array
    - [ ] Python Builtin ->
    - [x] Vyxal style constants?
    - [ ] Map and
    - [x] Functions
    - [x] Join for arrays.
    - [x] #6
    - [x] Sum array
    - [x] Random
    - [x] Slice
    - [ ] reduce
    - [x] Power
- [x]  Stricter checking for operations.
- [x] Add conversions:
    - [x] `Number` to `Binary` representation.
        - `lambda n:map(int,bin(n)[2:])`
    - [x] `String` to `Array` of `Number` or just a `Number` if `len(String) == 1`
- [x] Add docs
- [x] Single input command
- [x] Make a `code_page.txt`.
- [x] Match code_page chars with ascii chars

**Comment by lyxal** [comment]
Epic

**Comment by zoomlogo** [comment]
@Lyxal  i know :-)
